execution:
- threadNumber: ${__P(threadNumber)}
  duration: ${__P(duration)}
  ramp-up: ${__P(ramp-up)}
  scenario: simple  

scenarios:
  simple:
    script: internet-serwis-cabp.jmx
    
reporting:
- module: final-stats
  summary: true
  percentiles: true 
  failed-labels: false
  test-duration: true
  dump-csv: TaurusResult/perf_result_csv.csv
- module: passfail
  criteria:
  - "avg-rt>10s for 10s, stop as failed"
  - "fail>3% for 10s, stop as failed"
