execution:
- scenario: simple  

scenarios:
  simple:
    script: internet-serwis-cabp.jmx
    
reporting:
- module: final-stats
  summary: true
  percentiles: true 
  failed-labels: false
  test-duration: true
  dump-csv: TaurusResult/perf_result_csv.csv
- module: passfail
  criteria:
  - "avg-rt>10s for 10s, stop as failed"
  - "fail>3% for 10s, stop as failed"
- module: junit-xml
  data-source: pass-fail
  filename: TaurusResult/junit-result-passfail.xml
- module: junit-xml
  filename: TaurusResult/junit-result.xml
